(() => {
  'use strict';
  const qs = s => document.querySelector(s);
  const params = new URLSearchParams(location.search);
  const initialRoom = (params.get('room') || '').trim().toUpperCase();
  const isNew = params.get('new') === '1';
  const name = (params.get('name') || '').trim().slice(0, 40);
  const clientIdKey = 'classroom-live-client-id';
  let clientId = localStorage.getItem(clientIdKey);
  if (!clientId) { clientId = crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`; localStorage.setItem(clientIdKey, clientId); }

  const state = { phase:'IDLE', roomId:initialRoom, name, role:null, participantId:null, participants:new Map(), peers:new Map(), localStream:null, micOn:true, cameraOn:true, screenSharing:false, screenTrack:null, socket:null, lobbyReady:false, audioOnly:false, locked:false, handRaised:false, reconnectTimer:null, statsTimer:null, micAnalyser:null, micAudioContext:null, unread:0 };

  const el = { grid:qs('#grid'), lobby:qs('#lobby'), localPreview:qs('#localPreview'), previewFallback:qs('#previewFallback'), lobbyError:qs('#lobbyError'), roomCode:qs('#roomCode'), connection:qs('#connectionLabel'), micStatus:qs('#micStatus'), camStatus:qs('#camStatus'), participantList:qs('#participantList'), count:qs('#countBadge'), chatMessages:qs('#chatMessages'), chatForm:qs('#chatForm'), chatInput:qs('#chatInput'), unread:qs('#unread'), sidebar:qs('#sidebar'), moreMenu:qs('#moreMenu'), settings:qs('#settingsModal'), micSelect:qs('#micSelect'), camSelect:qs('#camSelect'), connectionDetails:qs('#connectionDetails'), toast:qs('#toast') };

  function setPhase(p){state.phase=p; const labels={IDLE:'Idle',LOBBY:'Lobby',CONNECTING:'Connecting…',CONNECTED:'Connected',RECONNECTING:'Reconnecting…',DISCONNECTED:'Disconnected',ENDING:'Ending…',ENDED:'Ended'}; el.connection.textContent=labels[p]||p;}
  function toast(msg){el.toast.textContent=msg;el.toast.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.toast.classList.remove('show'),2600);}
  function initials(n){return (n||'?').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase()||'?';}
  function escapeRoom(){return state.roomId || '—';}
  function participant(id){return state.participants.get(id);}
  function addParticipant(p){if(!p||!p.id)return;state.participants.set(p.id,p);renderParticipants();renderCard(p);}
  function renderParticipants(){el.count.textContent=state.participants.size;el.participantList.textContent='';for(const p of state.participants.values()){const row=document.createElement('div');row.className='person';const av=document.createElement('div');av.className='mini-avatar';av.textContent=initials(p.name);const info=document.createElement('div');info.className='person-info';const b=document.createElement('b');b.textContent=p.name+(p.id===state.participantId?' (You)':'');const s=document.createElement('span');s.textContent=p.role==='teacher'?'Teacher':'Student';info.append(b,s);const icons=document.createElement('div');icons.className='person-icons';icons.textContent=`${p.micOn?'🎤':'🔇'} ${p.cameraOn?'📷':'◼'}${p.handRaised?' ✋':''}`;row.append(av,info,icons);if(state.role==='teacher'&&p.id!==state.participantId){row.title='Click to remove participant';row.style.cursor='pointer';row.onclick=()=>{if(confirm(`Remove ${p.name}?`))state.socket.emit('remove-participant',{participantId:p.id});}}el.participantList.append(row);}}
  function renderCard(p){let card=document.getElementById(`card-${p.id}`);if(!card){card=document.createElement('div');card.className='video-card';card.id=`card-${p.id}`;const video=document.createElement('video');video.id=`video-${p.id}`;video.autoplay=true;video.playsInline=true;const fallback=document.createElement('div');fallback.id=`fallback-${p.id}`;fallback.className='avatar hidden';const label=document.createElement('div');label.className='video-label';const nm=document.createElement('span');nm.className='name';const st=document.createElement('span');st.className='badge';label.append(nm,st);card.append(video,fallback,label);el.grid.append(card);}const video=qs(`#video-${p.id}`),fallback=qs(`#fallback-${p.id}`);qs(`#card-${p.id} .name`).textContent=p.name+(p.role==='teacher'?' · Teacher':'');qs(`#card-${p.id} .badge`).textContent=`${p.micOn?'🎤':'🔇'} ${p.cameraOn?'📷':'Camera off'}${p.handRaised?' · ✋ Raised':''}`;fallback.textContent=initials(p.name);fallback.classList.toggle('hidden',p.cameraOn);video.classList.toggle('hidden',!p.cameraOn);if(p.id===state.participantId&&state.localStream){video.srcObject=state.localStream;video.muted=true;video.play().catch(()=>{});}}
  function removeCard(id){document.getElementById(`card-${id}`)?.remove();}
  function cleanupPeer(id){const item=state.peers.get(id);if(!item)return;try{item.pc.ontrack=null;item.pc.onicecandidate=null;item.pc.onconnectionstatechange=null;item.pc.close();}catch{}state.peers.delete(id);removeCard(id);}
  function cleanupAllPeers(){for(const id of [...state.peers.keys()])cleanupPeer(id);}

  async function getMedia(preview=true){
    if(!navigator.mediaDevices?.getUserMedia){throw new Error('This browser does not support camera/microphone access.');}
    const base={audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1},video:{width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30},facingMode:{ideal:'user'}}};
    try{return await navigator.mediaDevices.getUserMedia(base);}catch(first){
      try{return await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:true,noiseSuppression:true,autoGainControl:true},video:{width:{ideal:960},height:{ideal:540},frameRate:{ideal:24}}});}
      catch(second){try{return await navigator.mediaDevices.getUserMedia({audio:true,video:false});}catch(third){throw new Error('Microphone and camera are unavailable. You can continue only if the browser grants at least one media device.');}}
    }
  }
  async function prepareLobby(){setPhase('LOBBY');el.lobby.classList.remove('hidden');try{state.localStream=await getMedia();state.micOn=state.localStream.getAudioTracks().some(t=>t.enabled);state.cameraOn=state.localStream.getVideoTracks().some(t=>t.enabled);el.localPreview.srcObject=state.localStream;el.localPreview.play().catch(()=>{});el.previewFallback.classList.toggle('hidden',state.cameraOn);setupMicMeter();updateLobbyStatus();}catch(e){el.lobbyError.textContent=e.message;state.localStream=new MediaStream();state.cameraOn=false;state.micOn=false;updateLobbyStatus();}}
  function updateLobbyStatus(){el.micStatus.textContent=`Microphone: ${state.micOn?'ready':'off / unavailable'}`;el.camStatus.textContent=`Camera: ${state.cameraOn?'ready':'off / unavailable'}`;el.previewFallback.classList.toggle('hidden',state.cameraOn);}
  function setupMicMeter(){try{const track=state.localStream?.getAudioTracks()[0];if(!track)return;state.micAudioContext=new AudioContext();const source=state.micAudioContext.createMediaStreamSource(new MediaStream([track]));state.micAnalyser=state.micAudioContext.createAnalyser();state.micAnalyser.fftSize=256;source.connect(state.micAnalyser);}catch{}}
  async function stopMicMeter(){try{await state.micAudioContext?.close();}catch{}state.micAudioContext=null;state.micAnalyser=null;}
  function micLevel(){if(!state.micAnalyser)return 0;const a=new Uint8Array(state.micAnalyser.fftSize);state.micAnalyser.getByteTimeDomainData(a);let sum=0;for(const v of a){const x=(v-128)/128;sum+=x*x;}return Math.sqrt(sum/a.length);}

  function connectSocket(){
    state.socket=io({transports:['websocket','polling'],reconnection:true,reconnectionAttempts:Infinity,reconnectionDelay:800,reconnectionDelayMax:5000});
    state.socket.on('connect',async()=>{setPhase(state.participantId?'RECONNECTING':'CONNECTING');await joinOrCreate();});
    state.socket.on('disconnect',()=>{if(state.phase!=='ENDING'&&state.phase!=='ENDED')setPhase('RECONNECTING');});
    state.socket.io.on('reconnect_attempt',()=>setPhase('RECONNECTING'));
    state.socket.on('connect_error',()=>setPhase('RECONNECTING'));
    state.socket.on('room-created',({roomId})=>{state.roomId=roomId;el.roomCode.textContent=roomId;history.replaceState({},'',`/meeting.html?room=${roomId}&name=${encodeURIComponent(state.name)}`);});
    state.socket.on('room-state',data=>{state.roomId=data.roomId;state.locked=!!data.locked;el.roomCode.textContent=state.roomId;syncParticipants(data.participants||[]);});
    state.socket.on('participant-joined',async({participant:p})=>{addParticipant(p);if(p.id!==state.participantId)await makeOffer(p.id);});
    state.socket.on('participant-left',({participantId})=>{cleanupPeer(participantId);state.participants.delete(participantId);renderParticipants();});
    state.socket.on('signal-offer',async({from,offer})=>{try{await handleOffer(from,offer);}catch(e){console.warn('[WEBRTC] offer',e);}});
    state.socket.on('signal-answer',async({from,answer})=>{const item=state.peers.get(from);if(!item)return;try{await item.pc.setRemoteDescription(answer);await flushIce(item);}catch(e){console.warn('[WEBRTC] answer',e);}});
    state.socket.on('signal-ice',async({from,candidate})=>{const item=state.peers.get(from);if(!item)return;try{if(item.pc.remoteDescription)item.pc.addIceCandidate(candidate);else item.iceQueue.push(candidate);}catch(e){console.warn('[WEBRTC] ICE',e);}});
    state.socket.on('media-state',({participantId,micOn,cameraOn,screenSharing})=>{const p=participant(participantId);if(!p)return;Object.assign(p,{micOn,cameraOn,screenSharing});renderParticipants();renderCard(p);});
    state.socket.on('hand-raised',({participantId,raised})=>{const p=participant(participantId);if(!p)return;p.handRaised=raised;renderParticipants();renderCard(p);});
    state.socket.on('chat-message',msg=>addChat(msg));
    state.socket.on('participant-removed',({reason})=>{toast(reason||'You were removed from the meeting.');leaveLocal(false);location.href='/';});
    state.socket.on('meeting-locked',({locked})=>{state.locked=locked;updateHostMenu();toast(locked?'Meeting locked':'Meeting unlocked');});
    state.socket.on('host-changed',({hostId,participant:p})=>{state.role=hostId===state.participantId?'teacher':state.role;state.participants.set(p.id,p);renderParticipants();updateHostMenu();});
    state.socket.on('meeting-ended',({message})=>{toast(message||'Meeting ended by host.');leaveLocal(false);setTimeout(()=>location.href='/',400);});
  }
  function syncParticipants(list){for(const old of state.participants.keys())if(!list.some(p=>p.id===old)){cleanupPeer(old);state.participants.delete(old);}for(const p of list){state.participants.set(p.id,p);renderCard(p);}renderParticipants();updateHostMenu();setPhase('CONNECTED');startStats();}
  function joinOrCreate(){return new Promise(resolve=>{if(isNew&&!state.roomId){state.socket.emit('create-room',{name:state.name,clientId},res=>{if(!res?.ok){showFatal(res?.error||'Unable to create meeting.');return resolve();}applyJoinResult(res);resolve();});}else{state.socket.emit('join-room',{roomId:state.roomId,name:state.name,clientId},res=>{if(!res?.ok){showFatal(res?.error||'Unable to join meeting.');return resolve();}applyJoinResult(res);resolve();});}});}
  function applyJoinResult(res){state.roomId=res.roomId;state.participantId=res.participant.id;state.role=res.participant.role;state.locked=!!res.locked;state.participants.clear();for(const p of (res.participants||[]))state.participants.set(p.id,p);el.roomCode.textContent=state.roomId;history.replaceState({},'',`/meeting.html?room=${state.roomId}&name=${encodeURIComponent(state.name)}`);syncParticipants(res.participants||[]);updateHostMenu();for(const p of state.participants.values())if(p.id!==state.participantId)makeOffer(p.id);}
  function showFatal(msg){el.lobby.classList.remove('hidden');el.lobbyError.textContent=msg;qs('#joinNow').disabled=true;setPhase('DISCONNECTED');}

  function makePeer(id){if(state.peers.has(id))return state.peers.get(id);const config={iceServers:iceServers()};const pc=new RTCPeerConnection(config);const item={pc,iceQueue:[],makingOffer:false,ignoreOffer:false};state.peers.set(id,item);for(const t of state.localStream?.getTracks()||[])pc.addTrack(t,state.localStream);pc.onicecandidate=e=>{if(e.candidate)state.socket.emit('signal-ice',{to:id,candidate:e.candidate});};pc.ontrack=e=>{const p=participant(id);if(!p)return;renderCard(p);const v=qs(`#video-${id}`);if(v.srcObject!==e.streams[0]){v.srcObject=e.streams[0];v.muted=false;v.volume=1;v.play().catch(()=>{});}};pc.onconnectionstatechange=()=>{if(pc.connectionState==='failed'){try{pc.restartIce();}catch{}setTimeout(()=>{if(pc.connectionState==='failed')makeOffer(id,true);},1500);}if(pc.connectionState==='closed')cleanupPeer(id);};pc.oniceconnectionstatechange=()=>{if(pc.iceConnectionState==='failed'){try{pc.restartIce();}catch{}}};return item;}
  function iceServers(){const list=[];if(window.__ICE_CONFIG?.stun)list.push({urls:window.__ICE_CONFIG.stun});else list.push({urls:'stun:stun.l.google.com:19302'});if(window.__ICE_CONFIG?.turn)list.push({urls:window.__ICE_CONFIG.turn,username:window.__ICE_CONFIG.username,credential:window.__ICE_CONFIG.credential});return list;}
  async function makeOffer(id,force=false){const item=makePeer(id);const pc=item.pc;if(!force&&pc.signalingState!=='stable')return;try{item.makingOffer=true;const offer=await pc.createOffer({offerToReceiveAudio:true,offerToReceiveVideo:true});await pc.setLocalDescription(offer);state.socket.emit('signal-offer',{to:id,offer:pc.localDescription});}catch(e){console.warn('[WEBRTC] createOffer',e)}finally{item.makingOffer=false;}}
  async function handleOffer(id,offer){const item=makePeer(id);const pc=item.pc;const collision=item.makingOffer||pc.signalingState!=='stable';if(collision){item.ignoreOffer=true;return;}item.ignoreOffer=false;await pc.setRemoteDescription(offer);await flushIce(item);const answer=await pc.createAnswer();await pc.setLocalDescription(answer);state.socket.emit('signal-answer',{to:id,answer:pc.localDescription});}
  async function flushIce(item){while(item.iceQueue.length){const c=item.iceQueue.shift();try{await item.pc.addIceCandidate(c);}catch{}}}

  async function toggleMic(){const t=state.localStream?.getAudioTracks()[0];if(!t)return toast('Microphone is unavailable.');t.enabled=!t.enabled;state.micOn=t.enabled;const p=participant(state.participantId);if(p){p.micOn=t.enabled;renderCard(p);renderParticipants();}state.socket?.emit('media-state',{micOn:t.enabled});}
  async function toggleCam(){const t=state.localStream?.getVideoTracks()[0];if(!t)return toast('Camera is unavailable.');t.enabled=!t.enabled;state.cameraOn=t.enabled;const p=participant(state.participantId);if(p){p.cameraOn=t.enabled;renderCard(p);renderParticipants();}state.socket?.emit('media-state',{cameraOn:t.enabled});}
  async function toggleScreen(){if(state.screenSharing)return stopScreenShare();if(!navigator.mediaDevices?.getDisplayMedia)return toast('Screen sharing is not supported here.');try{const stream=await navigator.mediaDevices.getDisplayMedia({video:true,audio:false});const track=stream.getVideoTracks()[0];state.screenTrack=track;state.screenSharing=true;for(const item of state.peers.values()){const sender=item.pc.getSenders().find(s=>s.track?.kind==='video');if(sender)await sender.replaceTrack(track);}track.onended=stopScreenShare;state.socket.emit('media-state',{screenSharing:true});const p=participant(state.participantId);if(p){p.screenSharing=true;renderCard(p);}toast('Screen sharing started.');}catch(e){if(e.name!=='AbortError')toast('Unable to start screen sharing.');}}
  async function stopScreenShare(){if(!state.screenTrack)return;const cam=state.localStream?.getVideoTracks()[0];for(const item of state.peers.values()){const sender=item.pc.getSenders().find(s=>s.track?.kind==='video');if(sender)await sender.replaceTrack(cam||null);}state.screenTrack.stop();state.screenTrack=null;state.screenSharing=false;state.socket.emit('media-state',{screenSharing:false});const p=participant(state.participantId);if(p){p.screenSharing=false;renderCard(p);}}
  function toggleHand(){state.handRaised=!state.handRaised;const p=participant(state.participantId);if(p){p.handRaised=state.handRaised;renderCard(p);renderParticipants();}state.socket.emit('hand-raised',{raised:state.handRaised});}
  function toggleAudioOnly(){state.audioOnly=!state.audioOnly;document.body.classList.toggle('audio-only',state.audioOnly);for(const p of state.participants.values()){const v=qs(`#video-${p.id}`);if(v)v.classList.toggle('hidden',state.audioOnly||!p.cameraOn);}toast(state.audioOnly?'Audio-only mode on':'Video restored');}
  function addChat(msg){const div=document.createElement('div');div.className='message';const b=document.createElement('b');b.textContent=msg.name;const p=document.createElement('p');p.textContent=msg.text;const time=document.createElement('time');time.textContent=new Date(msg.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'});div.append(b,p,time);el.chatMessages.append(div);el.chatMessages.scrollTop=el.chatMessages.scrollHeight;if(el.sidebar.classList.contains('open')===false&&msg.participantId!==state.participantId){state.unread++;el.unread.textContent=state.unread;el.unread.classList.remove('hidden');}}

  async function populateDevices(){if(!navigator.mediaDevices?.enumerateDevices)return;const devices=await navigator.mediaDevices.enumerateDevices();el.micSelect.textContent='';el.camSelect.textContent='';for(const d of devices){if(d.kind==='audioinput'){const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||'Microphone';el.micSelect.append(o);}if(d.kind==='videoinput'){const o=document.createElement('option');o.value=d.deviceId;o.textContent=d.label||'Camera';el.camSelect.append(o);}}}
  async function applyDevices(){try{const constraints={audio:{deviceId:el.micSelect.value?{exact:el.micSelect.value}:undefined,echoCancellation:true,noiseSuppression:true,autoGainControl:true,channelCount:1},video:{deviceId:el.camSelect.value?{exact:el.camSelect.value}:undefined,width:{ideal:1280},height:{ideal:720},frameRate:{ideal:30,max:30}}};const fresh=await navigator.mediaDevices.getUserMedia(constraints);const old=state.localStream;state.localStream=fresh;old?.getTracks().forEach(t=>t.stop());el.localPreview.srcObject=fresh;const p=participant(state.participantId);if(p){state.micOn=!!fresh.getAudioTracks().length;state.cameraOn=!!fresh.getVideoTracks().length;p.micOn=state.micOn;p.cameraOn=state.cameraOn;renderCard(p);renderParticipants();}for(const item of state.peers.values())for(const sender of item.pc.getSenders()){const nt=fresh.getTracks().find(t=>t.kind===sender.track?.kind);if(nt)await sender.replaceTrack(nt);}el.settings.classList.add('hidden');toast('Devices updated.');}catch{toast('Unable to switch devices.');}}
  async function restartMedia(){try{const fresh=await getMedia();const old=state.localStream;state.localStream=fresh;old?.getTracks().forEach(t=>t.stop());el.localPreview.srcObject=fresh;for(const item of state.peers.values())for(const sender of item.pc.getSenders()){const nt=fresh.getTracks().find(t=>t.kind===sender.track?.kind);if(nt)await sender.replaceTrack(nt);}state.micOn=!!fresh.getAudioTracks().length;state.cameraOn=!!fresh.getVideoTracks().length;const p=participant(state.participantId);if(p){p.micOn=state.micOn;p.cameraOn=state.cameraOn;renderCard(p);renderParticipants();}toast('Camera and microphone restarted.');}catch{toast('Unable to restart media.');}}
  async function startStats(){clearInterval(state.statsTimer);state.statsTimer=setInterval(async()=>{let rtts=[],loss=0,total=0;for(const [id,item] of state.peers){try{const reports=await item.pc.getStats();reports.forEach(x=>{if(x.type==='candidate-pair'&&x.state==='succeeded'&&typeof x.currentRoundTripTime==='number')rtts.push(x.currentRoundTripTime*1000);if(x.type==='inbound-rtp'&&x.kind==='audio'){loss+=x.packetsLost||0;total+=x.packetsReceived||0;}});}catch{}}const avg=rtts.length?rtts.reduce((a,b)=>a+b,0)/rtts.length:null;let q='Excellent';if(avg>250||loss>20)q='Fair';if(avg>500||loss>80)q='Poor';if(avg>150)q='Good';el.connection.textContent=state.phase==='CONNECTED'?q:`${state.phase}`;el.connectionDetails.textContent=`Peers: ${state.peers.size}\nRTT: ${avg?Math.round(avg)+' ms':'—'}\nAudio packets lost: ${loss}/${total}`;adaptVideo(q);},5000);}
  async function adaptVideo(q){const desired=q==='Poor'?'low':q==='Fair'?'medium':'high';for(const item of state.peers.values()){try{const sender=item.pc.getSenders().find(s=>s.track?.kind==='video');if(!sender?.setParameters)continue;const p=sender.getParameters();p.encodings=p.encodings?.length?p.encodings:[{}];const max=q==='Poor'?350000:q==='Fair'?700000:1500000;p.encodings.forEach(e=>{e.maxBitrate=max;e.maxFramerate=q==='Poor'?15:24;});await sender.setParameters(p);}catch{}}}

  function updateHostMenu(){document.querySelectorAll('.host-only').forEach(x=>x.classList.toggle('hidden',state.role!=='teacher'));qs('#lockBtn').textContent=state.locked?'Unlock meeting':'Lock meeting';}
  async function leaveLocal(notify=true){state.phase='ENDING';clearInterval(state.statsTimer);clearTimeout(state.reconnectTimer);await stopScreenShare();cleanupAllPeers();await stopMicMeter();state.localStream?.getTracks().forEach(t=>t.stop());state.localStream=null;if(notify)state.socket?.emit('leave-room');state.socket?.disconnect();}
  function copy(text,msg){navigator.clipboard?.writeText(text).then(()=>toast(msg)).catch(()=>toast('Copy is unavailable in this browser.'));}
  function wire(){
    qs('#joinNow').onclick=async()=>{state.lobbyReady=true;el.lobby.classList.add('hidden');setPhase('CONNECTING');connectSocket();};
    qs('#lobbyMic').onclick=toggleMic;qs('#lobbyCam').onclick=toggleCam;qs('#toggleMic').onclick=toggleMic;qs('#toggleCam').onclick=toggleCam;qs('#shareScreen').onclick=toggleScreen;qs('#raiseHand').onclick=toggleHand;
    qs('#toggleChat').onclick=()=>{el.sidebar.classList.add('open');state.unread=0;el.unread.classList.add('hidden');};qs('#togglePeople').onclick=()=>el.sidebar.classList.toggle('open');
    qs('#moreBtn').onclick=()=>{const open=!el.moreMenu.classList.contains('hidden');el.moreMenu.classList.toggle('hidden',open);qs('#moreBtn').setAttribute('aria-expanded',String(!open));};
    qs('#audioOnly').onclick=toggleAudioOnly;qs('#fullscreen').onclick=()=>document.documentElement.requestFullscreen?.();qs('#pip').onclick=async()=>{const v=[...el.grid.querySelectorAll('video')].find(x=>!x.classList.contains('hidden'));if(!v)return toast('No video available.');try{if(v.requestPictureInPicture)await v.requestPictureInPicture();else toast('Picture in Picture is not supported.');}catch{toast('Picture in Picture is unavailable.');}};qs('#restartMedia').onclick=restartMedia;qs('#deviceSettings').onclick=async()=>{await populateDevices();el.settings.classList.remove('hidden');};qs('#closeSettings').onclick=()=>el.settings.classList.add('hidden');qs('#applyDevices').onclick=applyDevices;
    qs('#connectionInfo').onclick=()=>{el.settings.classList.remove('hidden');el.connectionDetails.textContent=el.connectionDetails.textContent||'Collecting connection statistics…';};qs('#lockBtn').onclick=()=>state.socket.emit('set-lock',{locked:!state.locked});qs('#endBtn').onclick=()=>{if(confirm('End the meeting for everyone?')){setPhase('ENDING');state.socket.emit('end-meeting');}};qs('#leaveBtn').onclick=()=>{if(confirm('Leave this meeting?')){leaveLocal(true).then(()=>location.href='/');}};qs('#leaveTop').onclick=()=>qs('#leaveBtn').click();
    qs('#copyRoom').onclick=()=>copy(state.roomId,'Room code copied.');qs('#copyLink').onclick=()=>copy(`${location.origin}/meeting.html?room=${encodeURIComponent(state.roomId)}`,'Invite link copied.');
    el.chatForm.onsubmit=e=>{e.preventDefault();const text=el.chatInput.value.trim();if(!text)return;state.socket?.emit('chat-message',{text});el.chatInput.value='';};
    navigator.mediaDevices?.addEventListener?.('devicechange',populateDevices);
  }
  async function init(){if(!name){location.href='/';return;}el.roomCode.textContent=initialRoom||'Creating…';wire();await prepareLobby();}
  init();
})();
